#!/bin/bash

set -x
set -e

echo "prepare index.html ..."

cd $(dirname $0)/..

ls -alF data/ data.in/

inliner -debug -m data.in/index.html
inliner -debug -m data.in/index.html > data/index.html

ls -alF data/ data.in/

gzip -n -f -9 data/index.html

ls -alF data/ data.in/

echo "... done!"
